In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf
import statsmodels.api as sm
from statsmodels.graphics.regressionplots import influence_plot

In [2]:
toy = pd.read_csv("ToyotaCorolla.csv",encoding = 'latin2')
toy

,Id,Model,Price,Age_08_04,Mfg_Month,Mfg_Year,KM,Fuel_Type,HP,Met_Color,...,Central_Lock,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Tow_Bar
0,1,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13500,23,10,2002,46986,Diesel,90,1,...,1,1,1,0,0,0,1,0,0,0
1,2,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13750,23,10,2002,72937,Diesel,90,1,...,1,0,1,0,0,0,1,0,0,0
2,3,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13950,24,9,2002,41711,Diesel,90,1,...,0,0,1,0,0,0,1,0,0,0
3,4,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,14950,26,7,2002,48000,Diesel,90,0,...,0,0,1,0,0,0,1,0,0,0
4,5,TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors,13750,30,3,2002,38500,Diesel,90,0,...,1,1,1,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1431,1438,TOYOTA Corolla 1.3 16V HATCHB G6 2/3-Doors,7500,69,12,1998,20544,Petrol,86,1,...,1,1,1,0,1,1,1,0,0,0
1432,1439,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,10845,72,9,1998,19000,Petrol,86,0,...,0,0,1,0,0,1,1,0,0,0
1433,1440,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,8500,71,10,1998,17016,Petrol,86,0,...,0,0,1,0,0,0,1,0,0,0
1434,1441,TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...,7250,70,11,1998,16916,Petrol,86,1,...,0,0,0,0,0,0,1,0,0,0
1435,1442,TOYOTA Corolla 1.6 LB LINEA TERRA 4/5-Doors,6950,76,5,1998,1,Petrol,110,0,...,0,0,1,0,0,0,0,0,0,0

In [3]:
toyo = toy[["Price","Age_08_04","KM","HP","cc","Doors","Gears","Quarterly_Tax","Weight"]]
toyo

      Price  Age_08_04     KM   HP    cc  Doors  Gears  Quarterly_Tax  Weight
0     13500         23  46986   90  2000      3      5            210    1165
1     13750         23  72937   90  2000      3      5            210    1165
2     13950         24  41711   90  2000      3      5            210    1165
3     14950         26  48000   90  2000      3      5            210    1165
4     13750         30  38500   90  2000      3      5            210    1170
...     ...        ...    ...  ...   ...    ...    ...            ...     ...
1431   7500         69  20544   86  1300      3      5             69    1025
1432  10845         72  19000   86  1300      3      5             69    1015
1433   8500         71  17016   86  1300      3      5             69    1015
1434   7250         70  16916   86  1300      3      5             69    1015
1435   6950         76      1  110  1600      5      5             19    1114

[1436 rows x 9 columns]

In [4]:
toyo1 = toyo.rename({"Age_08_04":"Age","cc":"CC","Quarterly_Tax":"QT"}, axis = 1)
toyo1

      Price  Age     KM   HP    CC  Doors  Gears   QT  Weight
0     13500   23  46986   90  2000      3      5  210    1165
1     13750   23  72937   90  2000      3      5  210    1165
2     13950   24  41711   90  2000      3      5  210    1165
3     14950   26  48000   90  2000      3      5  210    1165
4     13750   30  38500   90  2000      3      5  210    1170
...     ...  ...    ...  ...   ...    ...    ...  ...     ...
1431   7500   69  20544   86  1300      3      5   69    1025
1432  10845   72  19000   86  1300      3      5   69    1015
1433   8500   71  17016   86  1300      3      5   69    1015
1434   7250   70  16916   86  1300      3      5   69    1015
1435   6950   76      1  110  1600      5      5   19    1114

[1436 rows x 9 columns]

In [5]:
toyo1.head(11)

    Price  Age     KM   HP    CC  Doors  Gears   QT  Weight
0   13500   23  46986   90  2000      3      5  210    1165
1   13750   23  72937   90  2000      3      5  210    1165
2   13950   24  41711   90  2000      3      5  210    1165
3   14950   26  48000   90  2000      3      5  210    1165
4   13750   30  38500   90  2000      3      5  210    1170
5   12950   32  61000   90  2000      3      5  210    1170
6   16900   27  94612   90  2000      3      5  210    1245
7   18600   30  75889   90  2000      3      5  210    1245
8   21500   27  19700  192  1800      3      5  100    1185
9   12950   23  71138   69  1900      3      5  185    1105
10  20950   25  31461  192  1800      3      6  100    1185

In [6]:
toyo1.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1431    False
1432    False
1433    False
1434    False
1435    False
Length: 1436, dtype: bool

In [7]:
toyo1.describe()

,Price,Age,KM,HP,CC,Doors,Gears,QT,Weight
count,1436.000000,1436.000000,1436.000000,1436.000000,1436.00000,1436.000000,1436.000000,1436.000000,1436.00000
mean,10730.824513,55.947075,68533.259749,101.502089,1576.85585,4.033426,5.026462,87.122563,1072.45961
std,3626.964585,18.599988,37506.448872,14.981080,424.38677,0.952677,0.188510,41.128611,52.64112
min,4350.000000,1.000000,1.000000,69.000000,1300.00000,2.000000,3.000000,19.000000,1000.00000
25%,8450.000000,44.000000,43000.000000,90.000000,1400.00000,3.000000,5.000000,69.000000,1040.00000
50%,9900.000000,61.000000,63389.500000,110.000000,1600.00000,4.000000,5.000000,85.000000,1070.00000
75%,11950.000000,70.000000,87020.750000,110.000000,1600.00000,5.000000,5.000000,85.000000,1085.00000
max,32500.000000,80.000000,243000.000000,192.000000,16000.00000,5.000000,6.000000,283.000000,1615.00000

In [8]:
toyo1.corr()

,Price,Age,KM,HP,CC,Doors,Gears,QT,Weight
Price,1.000000,-0.876590,-0.569960,0.314990,0.126389,0.185326,0.063104,0.219197,0.581198
Age,-0.876590,1.000000,0.505672,-0.156622,-0.098084,-0.148359,-0.005364,-0.198431,-0.470253
KM,-0.569960,0.505672,1.000000,-0.333538,0.102683,-0.036197,0.015023,0.278165,-0.028598
HP,0.314990,-0.156622,-0.333538,1.000000,0.035856,0.092424,0.209477,-0.298432,0.089614
CC,0.126389,-0.098084,0.102683,0.035856,1.000000,0.079903,0.014629,0.306996,0.335637
Doors,0.185326,-0.148359,-0.036197,0.092424,0.079903,1.000000,-0.160141,0.109363,0.302618
Gears,0.063104,-0.005364,0.015023,0.209477,0.014629,-0.160141,1.000000,-0.005452,0.020613
QT,0.219197,-0.198431,0.278165,-0.298432,0.306996,0.109363,-0.005452,1.000000,0.626134
Weight,0.581198,-0.470253,-0.028598,0.089614,0.335637,0.302618,0.020613,0.626134,1.000000

In [9]:
toyo1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   1436 non-null   int64
 1   Age     1436 non-null   int64
 2   KM      1436 non-null   int64
 3   HP      1436 non-null   int64
 4   CC      1436 non-null   int64
 5   Doors   1436 non-null   int64
 6   Gears   1436 non-null   int64
 7   QT      1436 non-null   int64
 8   Weight  1436 non-null   int64
dtypes: int64(9)
memory usage: 101.1 KB

In [10]:
toyo1.isnull()

      Price    Age     KM     HP     CC  Doors  Gears     QT  Weight
0     False  False  False  False  False  False  False  False   False
1     False  False  False  False  False  False  False  False   False
2     False  False  False  False  False  False  False  False   False
3     False  False  False  False  False  False  False  False   False
4     False  False  False  False  False  False  False  False   False
...     ...    ...    ...    ...    ...    ...    ...    ...     ...
1431  False  False  False  False  False  False  False  False   False
1432  False  False  False  False  False  False  False  False   False
1433  False  False  False  False  False  False  False  False   False
1434  False  False  False  False  False  False  False  False   False
1435  False  False  False  False  False  False  False  False   False

[1436 rows x 9 columns]

In [11]:
toyo1[toyo1.duplicated()]

     Price  Age     KM   HP    CC  Doors  Gears   QT  Weight
113  24950    8  13253  116  2000      5      5  234    1320

In [13]:
toyo2 = toyo1.drop_duplicates().reset_index(drop=True)
toyo2

      Price  Age     KM   HP    CC  Doors  Gears   QT  Weight
0     13500   23  46986   90  2000      3      5  210    1165
1     13750   23  72937   90  2000      3      5  210    1165
2     13950   24  41711   90  2000      3      5  210    1165
3     14950   26  48000   90  2000      3      5  210    1165
4     13750   30  38500   90  2000      3      5  210    1170
...     ...  ...    ...  ...   ...    ...    ...  ...     ...
1430   7500   69  20544   86  1300      3      5   69    1025
1431  10845   72  19000   86  1300      3      5   69    1015
1432   8500   71  17016   86  1300      3      5   69    1015
1433   7250   70  16916   86  1300      3      5   69    1015
1434   6950   76      1  110  1600      5      5   19    1114

[1435 rows x 9 columns]

In [14]:
model = smf.ols("Price~Age+KM+Weight+HP+CC+Gears+QT+Doors", data = toyo2).fit()
model

In [15]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  Price   R-squared:                       0.863
Model:                            OLS   Adj. R-squared:                  0.862
Method:                 Least Squares   F-statistic:                     1118.
Date:                Thu, 16 Oct 2025   Prob (F-statistic):               0.00
Time:                        16:36:43   Log-Likelihood:                -12366.
No. Observations:                1435   AIC:                         2.475e+04
Df Residuals:                    1426   BIC:                         2.480e+04
Df Model:                           8
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -5472.5404   1412.169     -3.875      0.000   -8242.692   -2702.389
Age         -121.7139      2.615    -46.552      0.000    -126.843    -116.585
KM            -0.0207      0.001    -16.552      0.000      -0.023      -0.018
Weight        16.8555      1.069     15.761      0.000      14.758      18.953
HP            31.5846      2.818     11.210      0.000      26.058      37.112
CC            -0.1186      0.090     -1.316      0.188      -0.295       0.058
Gears        597.7159    196.969      3.035      0.002     211.335     984.097
QT             3.8588      1.311      2.944      0.003       1.288       6.430
Doors         -0.9202     39.988     -0.023      0.982     -79.362      77.522
==============================================================================
Omnibus:                      149.666   Durbin-Watson:                   1.544
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1000.538
Skew:                          -0.204   Prob(JB):                    5.44e-218
Kurtosis:                       7.070   Cond. No.                     3.13e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.13e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [16]:
#model 1- linear regression model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


X =toyo2[["Age","KM","HP","CC","Doors","Gears","QT","Weight"]]
y = toyo2[["Price"]]

model = LinearRegression()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model.fit(X_train,y_train)

LinearRegression()

In [18]:
from sklearn.metrics import mean_squared_error


y_pred = model.predict(X_test)
print(y_pred)
print(y_test)
err= mean_squared_error(y_test,y_pred)
print(err)

[[10626.92345443]
 [10369.96225533]
 [ 9513.41941395]
 [ 9507.76703383]
 [ 8491.23656271]
 [ 8317.06672326]
 [ 8171.07868485]
 [ 8366.68929033]
 [11813.87061057]
 [12473.19794146]
 [ 9343.43922395]
 [ 9433.05217934]
 [13255.33356983]
 [12388.84504024]
 [ 8895.83675558]
 [11616.47427334]
 [12373.94211528]
 [17558.89278609]
 [11291.94660793]
 [11621.75697129]
 [11640.12886613]
 [17982.65246996]
 [ 9942.81316866]
 [10515.59401719]
 [ 7263.91453085]
 [15972.12770274]
 [ 7088.40487346]
 [ 8569.79650173]
 [15461.78505142]
 [13930.07655625]
 [ 8147.98430757]
 [10983.90205419]
 [10146.22281057]
 [10141.0353864 ]
 [10191.64587983]
 [ 8582.12152914]
 [ 8909.22655119]
 [10005.60246173]
 [16158.06907892]
 [10747.73838458]
 [ 8544.77546384]
 [ 9585.7167111 ]
 [10129.38164164]
 [ 8532.21955621]
 [10676.75212392]
 [17421.00742698]
 [10046.7448345 ]
 [ 8883.92304329]
 [10862.67234939]
 [12830.46989646]
 [12951.33165063]
 [ 6291.51311956]
 [14643.39559258]
 [16226.7674985 ]
 [ 5832.64424251]
 [ 8213.62135488]
 [11464.00657617]
 [11605.52675089]
 [15961.38134911]
 [19437.34004512]
 [14178.1181469 ]
 [ 8221.82008614]
 [ 8490.4506814 ]
 [13056.698371  ]
 [12304.28637967]
 [ 6409.87586792]
 [13319.18922751]
 [ 7688.64925014]
 [ 8267.61558385]
 [ 6465.27846988]
 [20607.92576214]
 [10679.91902761]
 [14013.93169148]
 [ 7455.36096658]
 [17370.68000045]
 [11590.45274908]
 [ 7514.62328825]
 [ 7503.6853589 ]
 [ 9143.89791   ]
 [ 9944.08755073]
 [ 8247.10067923]
 [12200.62272564]
 [11486.51233114]
 [11324.11265358]
 [ 7483.43308703]
 [ 7433.61153691]
 [ 7928.1595679 ]
 [13270.22246082]
 [ 9612.57296636]
 [10909.04837127]
 [ 7770.49938211]
 [ 7164.51629992]
 [ 8081.87666447]
 [10851.26738886]
 [ 9236.07533138]
 [ 8990.72894853]
 [21380.45062829]
 [11284.4021317 ]
 [13582.54469742]
 [11358.88012167]
 [10876.74463781]
 [ 8687.79838157]
 [10888.7552522 ]
 [16602.09959116]
 [ 9566.41899295]
 [ 7634.91600637]
 [16747.50111611]
 [ 7692.52359149]
 [13352.36999945]
 [ 8654.86298621]
 [12683.11186439]
 [11785.22229695]
 [ 8621.12810305]
 [14123.50690642]
 [ 9349.10521388]
 [ 9425.96514689]
 [ 6387.77695398]
 [13817.05283267]
 [12581.56696191]
 [13316.31675107]
 [ 7847.71549029]
 [10612.50936424]
 [ 9783.87089866]
 [15195.23845276]
 [12642.37888451]
 [ 6369.55573761]
 [ 7911.97007751]
 [ 9644.26843344]
 [ 8547.42479769]
 [12255.98137395]
 [10915.84265502]
 [15426.95377179]
 [ 7369.91591838]
 [ 9451.2983534 ]
 [ 6434.5995536 ]
 [ 9271.38919532]
 [ 7857.30587948]
 [11597.62257753]
 [10592.68919983]
 [ 7593.90256679]
 [12168.75013639]
 [ 7925.6476568 ]
 [22822.28045274]
 [ 8359.48509961]
 [11360.48556937]
 [11362.86346141]
 [ 8396.51971065]
 [ 8586.49008079]
 [ 8279.98250759]
 [11330.81463875]
 [ 7739.1161968 ]
 [15910.60897474]
 [10114.37717725]
 [ 7979.86573535]
 [11926.39920215]
 [11070.31371664]
 [ 8729.34098752]
 [13048.55423078]
 [ 6279.3281606 ]
 [18866.76572496]
 [10673.60059044]
 [15419.09967354]
 [15171.43664838]
 [ 9018.83686773]
 [ 5913.34537787]
 [14052.91381491]
 [ 9582.17132572]
 [13462.06505727]
 [ 8163.44590334]
 [ 9279.51470813]
 [ 8097.59511882]
 [13035.46471118]
 [ 8811.0676442 ]
 [ 7260.47689965]
 [10441.11349159]
 [ 8714.47241391]
 [16624.78511397]
 [10184.64954726]
 [ 9748.61153524]
 [13566.3285695 ]
 [ 6779.81418785]
 [ 9920.24667388]
 [13532.12242877]
 [ 7783.9199015 ]
 [ 9239.54707014]
 [12931.25615756]
 [ 5859.59810013]
 [ 8206.98373454]
 [ 9269.01635003]
 [ 8083.61316636]
 [ 9149.57350706]
 [ 9710.02363573]
 [ 6095.58335364]
 [11246.34366974]
 [10116.17028549]
 [11604.11175767]
 [ 9813.65109838]
 [ 9499.06616399]
 [11130.13276237]
 [17615.00378042]
 [ 9565.15944329]
 [ 7654.14236466]
 [ 8460.23329029]
 [10252.93375548]
 [16029.02047969]
 [17033.19197997]
 [10817.19274857]
 [ 9474.0367538 ]
 [10063.28981913]
 [ 7789.99493169]
 [10814.84961304]
 [11194.68540369]
 [ 9759.63191457]
 [10202.21979535]
 [ 6966.40391182]
 [10300.67316987]
 [ 7745.03289709]
 [ 9902.51844355]
 [ 6729.99659352]
 [11556.80183569]
 [ 8533.22309986]
 [11128.07886444]
 [14321.95753385]
 [11008.3306193 ]
 [16730.62046868]
 [ 6447.7548904 ]
 [16025.51581598]
 [ 7325.51364564]
 [12870.86256604]
 [ 7295.66198383]
 [12972.32473653]
 [ 8581.83756798]
 [27031.68089241]
 [ 7813.71694884]
 [ 9370.3705145 ]
 [ 8237.25427641]
 [13015.4181793 ]
 [13378.49911105]
 [ 8540.47550106]
 [ 9692.30710091]
 [12461.45386439]
 [18818.68637724]
 [13598.29227162]
 [ 9595.93163018]
 [18204.07413075]
 [10213.35142916]
 [ 9645.75054296]
 [ 9769.22439305]
 [10099.87489703]
 [ 9103.40342549]
 [ 9236.1102866 ]
 [ 8257.24112735]
 [ 8593.45282858]
 [ 7693.10522108]
 [10494.84865612]
 [12203.83749105]
 [ 6652.28661687]
 [ 7527.15787965]
 [12901.46516723]
 [ 9574.22498097]
 [14053.07606344]
 [ 8453.62093082]
 [ 6151.59447867]
 [ 9214.60937738]
 [ 8713.40136673]
 [ 7027.56383163]
 [13010.76082842]
 [ 5217.87899194]
 [ 8571.51617957]
 [ 8866.65417888]
 [12823.35201087]
 [15491.57882836]
 [ 9172.88361438]
 [12948.85161813]
 [ 7728.1268992 ]
 [ 7264.41685214]
 [ 7009.36510494]
 [ 7681.59084475]
 [ 7186.52596321]
 [12843.09822575]
 [22367.86694761]
 [11085.13829782]
 [ 7205.77684308]
 [19071.44556996]
 [ 8085.71225356]
 [14108.02921919]
 [ 6486.41336107]]
      Price
752    9950
857    7995
629    7500
1411   9950
974    8950
...     ...
1112   5750
174   19950
1427   8450
297   13995
1125   6800

[287 rows x 1 columns]
1875973.861656942

In [20]:

err1 = y_test - y_pred
print(err1)

            Price
752   -676.923454
857  -2374.962255
629  -2013.419414
1411   442.232966
974    458.763437
...           ...
1112 -1455.776843
174    878.554430
1427   364.287746
297   -113.029219
1125   313.586639

[287 rows x 1 columns]